#spring.application.name=orderService

spring:
  application:
    name: orderService
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/orderDb
    password: 1234
    hikari:
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  spring:
    cloud:
      stream:
        function:
          definition: orderSuppliers;paymentEventConsumer
        bindings:
          orderSupplier-out-0:
            destination: order-event
          paymentEventConsumer-in-0:
            destination: payment-event


#order-event-topic name
  server:
    port: 8082